# Generated by Django 5.2.1 on 2025-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoItems',
        ),
    ]
