# Generated by Django 5.2.1 on 2025-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contatto_delete_todoitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatto',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='contatto',
            constraint=models.UniqueConstraint(fields=('nome', 'cognome', 'telefono'), name='unique_contatto'),
        ),
    ]
